---
openapi: 3.0.1
info:
  title: Good Night API
  version: v1
  description: API for tracking sleep records
paths:
  "/api/v1/users/{user_id}/relationships":
    parameters:
    - name: user_id
      in: path
      description: ID of the user who is following
      required: true
      schema:
        type: integer
    post:
      summary: Follows a user
      tags:
      - Relationships
      parameters: []
      responses:
        '201':
          description: user followed successfully
        '422':
          description: can't follow yourself
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                target_user_id:
                  type: integer
                  description: ID of the user to be followed
              required:
              - target_user_id
  "/api/v1/users/{user_id}/relationships/{target_user_id}":
    parameters:
    - name: user_id
      in: path
      description: ID of the user who is unfollowing
      required: true
      schema:
        type: integer
    - name: target_user_id
      in: path
      description: ID of the target user who is followed
      required: true
      schema:
        type: integer
    delete:
      summary: Unfollows a user
      tags:
      - Relationships
      responses:
        '204':
          description: user unfollowed successfully
        '422':
          description: can't unfollow an unfollowed user
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
  "/api/v1/users/{user_id}/sleep":
    parameters:
    - name: user_id
      in: path
      description: ID of the user
      required: true
      schema:
        type: integer
    post:
      summary: Creates a sleep record
      tags:
      - SleepRecords
      responses:
        '201':
          description: sleep record created successfully
        '404':
          description: user not found
        '422':
          description: user already has an ongoing sleep record
  "/api/v1/users/{user_id}/wake_up":
    parameters:
    - name: user_id
      in: path
      description: ID of the user
      required: true
      schema:
        type: integer
    post:
      summary: Updates a wake-up record
      tags:
      - SleepRecords
      responses:
        '201':
          description: wake up record created successfully
        '404':
          description: user not found
        '422':
          description: wake up already recorded
  "/api/v1/users":
    get:
      summary: Retrieves a list of users
      tags:
      - Users
      responses:
        '200':
          description: users found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/user"
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user_create"
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: User ID
      required: true
      schema:
        type: integer
    get:
      summary: Retrieve a user
      tags:
      - Users
      responses:
        '200':
          description: user exists
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
        '404':
          description: user not exists
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
    delete:
      summary: Deletes a user
      tags:
      - Users
      responses:
        '204':
          description: user deleted
        '404':
          description: user not exists
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alice
        created_at:
          type: string
          format: date-time
          example: '2023-10-26T10:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2023-10-26T10:00:00Z'
      required:
      - id
      - name
      - created_at
      - updated_at
    user_create:
      type: object
      properties:
        name:
          type: string
          example: Charlie
      required:
      - name
    errors:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              example: 422
              description: HTTP status code
            message:
              type: string
              example: This is error message
              description: General error message
            details:
              type: object
              description: Detailed error messages, keyed by attribute
              additionalProperties:
                type: array
                items:
                  type: string
                  example: can't be blank
                description: Array of error messages for a specific attribute
          required:
          - status
          - message
          - details
      required:
      - error
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
